# Generated by Django 4.0.4 on 2022-07-10 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_address',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='m_drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='m_email',
            field=models.EmailField(default='s201402644@hufs.ac.kr', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='m_intro',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='member',
            name='m_name',
            field=models.CharField(default='noname', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='m_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_post',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_rdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
