# Generated by Django 4.0.4 on 2022-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_m_address_member_m_buy_member_m_drop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
