# Generated by Django 4.0.4 on 2022-07-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_m_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='m_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='m_id'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='m_name'),
        ),
    ]
